# Generated by Django 2.2.4 on 2019-08-29 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot1', models.TextField()),
                ('slot2', models.TextField()),
                ('slot3', models.TextField()),
                ('slot4', models.TextField()),
                ('slot5', models.TextField()),
                ('slot6', models.TextField()),
                ('slot7', models.TextField()),
                ('slot8', models.TextField()),
                ('slot9', models.TextField()),
                ('hide1', models.BooleanField()),
                ('hide2', models.BooleanField()),
                ('hide3', models.BooleanField()),
                ('hide4', models.BooleanField()),
                ('hide5', models.BooleanField()),
                ('hide6', models.BooleanField()),
                ('hide7', models.BooleanField()),
                ('hide8', models.BooleanField()),
                ('hide9', models.BooleanField()),
                ('show1', models.BooleanField()),
                ('show2', models.BooleanField()),
                ('show3', models.BooleanField()),
                ('show4', models.BooleanField()),
                ('show5', models.BooleanField()),
                ('show6', models.BooleanField()),
                ('show7', models.BooleanField()),
                ('show8', models.BooleanField()),
                ('show9', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(to='page.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Interface')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.TextField()),
                ('results', models.BooleanField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Interface')),
                ('submitted', models.ManyToManyField(to='page.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(to='page.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Lecture'),
        ),
        migrations.AddField(
            model_name='interface',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Lecturer'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Interface')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_number', models.IntegerField()),
                ('correct', models.BooleanField()),
                ('students', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Question')),
            ],
        ),
    ]
