# Generated by Django 2.2.4 on 2019-08-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Interface')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Student')),
            ],
        ),
    ]
