# Generated by Django 2.2.3 on 2019-07-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.TextField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('correct', models.BooleanField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Interface')),
                ('question_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Question')),
            ],
        ),
    ]
