# Generated by Django 2.2.4 on 2019-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='results',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='submitted',
            field=models.ManyToManyField(to='page.Student'),
        ),
    ]
