# Generated by Django 2.2.3 on 2019-07-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_number',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='interface',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
