# Generated by Django 2.2.4 on 2019-08-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20190821_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Interface')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Student')),
            ],
        ),
    ]
