# Generated by Django 2.2.3 on 2019-07-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20190710_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='students',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
