# Generated by Django 2.2.4 on 2019-08-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20190828_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='hide',
        ),
    ]
